### ISSUE TITLE
Playing mono samples with libacm

### ISSUE THREAD

**Issue by winterheart** [markokr/libacm#2]
Hello!

We recently integrated libacm in our Descent 3 game project (https://github.com/DescentDevelopers/Descent3). It uses ACM audio files in both mono and stereo. After integration, we encountered a [problem](https://github.com/DescentDevelopers/Descent3/issues/180) that samples with one channel were cut off during playback. We found that in this case acm_open_decoder() with force_chans = 0 [forces](https://github.com/markokr/libacm/blob/master/src/decode.c#L814) two channels despite the correct ACM header.

Although we can do force_chans = 1/2, this requires separate processing of the ACM header, which is not optimal from the point of view of the logic of our code. Is it possible to remove this check in the code?

Proposed changes [here](https://github.com/DescentDevelopers/Descent3/pull/191).

**Comment by DanielGibson** [comment]
I have a better idea on how this can be handled in a way that keeps the existing behavior of libacm, but also allows telling it to trust the header.

See #3

**Comment by markokr** [comment]
Fixed by #3
